import coverGarotoAvatar from '../images/books/garoto-avatar-capa-11.jpg';
import coverTigres from '../images/books/tigres-do-rio-capa2.png';
import coverMenino from '../images/books/o-seu-menino-capa1.png';
import coverDemonho from '../images/books/demonho-capa-scaled1.png';
import coverMan from '../images/books/homem-da-cabeca-de-papelao-capa1.png'

export const Books = [
  {
    _id: '1',
    title: 'Garoto Avatar',
    authors: 'Caeto e Luana Vignon',
    ilustration: 'Caeto',
    size: '21 x 21 Colorido',
    pages: '56',
    ageIndication: 'A partir dos 9 anos. Indicado para leitores iniciantes',
    gender: 'Prosa narrativa (baseada na estética das histórias em quadrinhos)',
    themes: 'Comportamento, videogame, família',
    isbn: '978-65-81555-009',
    price: 'R$ 49,90',
    cover: coverGarotoAvatar,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: '2',
    title: 'Tigres do Rio',
    authors: 'Caeto',
    ilustration: 'Caeto',
    size: '16 x 23 Preto e Branco',
    pages: '56',
    ageIndication: 'A partir dos 15 anos. Indicado para leitores autônomos',
    gender: 'História em quadrinhos ',
    themes: 'Sociedade, comportamento, preconceito, racismo',
    isbn: '978-65-81555-01-6',
    price: 'R$ 29,90',
    cover: coverTigres,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: '3',
    title: 'ô, Seu Menino',
    authors: 'Lu Vitti;',
    ilustration: 'Guilherme Pires',
    size: '28 x 21 Colorido',
    pages: '40',
    ageIndication: 'A partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento',
    isbn: '978-65-991456-4-3',
    price: 'Em Breve',
    cover: coverMenino,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: '4',
    title: 'Demonho',
    authors: 'João do Rio',
    ilustration: 'Caeto',
    size: '21 x 21 Preto e Branco',
    pages: '56',
    ageIndication: 'A partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento.',
    isbn: '978-65-81555-02-3',
    price: 'R$ 29,90',
    cover: coverDemonho,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: '5',
    title: 'O Homem da Cabeça de Papelão',
    authors: 'João do Rio',
    ilustration: 'Caeto',
    size: '21 x 21 Preto e Branco',
    pages: '56',
    ageIndication: 'A  partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento',
    isbn: '978-65-81555-02-3',
    price: 'R$ 29,90',
    cover: coverMan,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: 'X',
    title: 'ô, Seu Menino',
    authors: 'Lu Vitti;',
    ilustration: 'Guilherme Pires',
    size: '28 x 21 Colorido',
    pages: '40',
    ageIndication: 'A partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento',
    isbn: '978-65-991456-4-3',
    price: 'Em Breve',
    cover: coverMenino,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: 'X',
    title: 'Demonho',
    authors: 'João do Rio',
    ilustration: 'Caeto',
    size: '21 x 21 Preto e Branco',
    pages: '56',
    ageIndication: 'A partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento.',
    isbn: '978-65-81555-02-3',
    price: 'R$ 29,90',
    cover: coverDemonho,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
  {
    _id: 'X',
    title: 'O Homem da Cabeça de Papelão',
    authors: 'João do Rio',
    ilustration: 'Caeto',
    size: '21 x 21 Preto e Branco',
    pages: '56',
    ageIndication: 'A  partir dos 11 anos. Indicado para leitores autônomos',
    gender: 'Prosa narrativa',
    themes: 'Sociedade e comportamento',
    isbn: '978-65-81555-02-3',
    price: 'R$ 29,90',
    cover: coverMan,
    cover3d: 'http://placekitten.com/300/470',
    image: 'http://placekitten.com/260/140',
  },
]